### ISSUE TITLE
Running tests with gulp

### ISSUE THREAD

**Issue by bestan** [wallabyjs/atom-wallaby#1]
I'm using gulp + mocha to run tests. In order to run specific tests I'm providing grep argument to mocha.

How does wallaby.js detect which tests to run? Is there a way for me to make it run gulp?

**Comment by ArtemGovorov** [comment]
Wallaby.js detects tests to run automatically, based on your code changes, so you don't have to pass anything - just edit your tests and code in the editor.

**Comment by bestan** [comment]
@ArtemGovorov I've tried that, but it's throwing errors on lines with require() with relative paths (no such module etc.). 

I assume it's running specific files rather than the main test file (hence the relative path issue), is that correct?

**Comment by ArtemGovorov** [comment]
First time it's running files specified in the `tests` list in your wallaby config file. If you are running node.js tests, make sure you've specified [your source files patterns correctly](http://wallabyjs.com/docs/intro/troubleshooting.html#39-cannot-find-module-39-or-39-file-not-found-39). Either way, could you please share your wallaby config file?

**Comment by bestan** [comment]
@ArtemGovorov thanks, that resolved the require issue. More than anything I was missing [a getting started guide for Atom](http://dm.gl/2015/08/31/wallaby-for-atom/), but you've already published that. Closing.
