### ISSUE TITLE
How do you do the gutters?

### ISSUE THREAD

**Issue by steelbrain** [wallabyjs/atom-wallaby#12]
I really like the way you have managed the gutter highlights, I dug through the docs and couldn't find how. What APIs did you use for it?

**Comment by steelbrain** [comment]
Nevermind, found it here https://atom.io/docs/api/v1.0.15/TextEditor#instance-addGutter

**Comment by ArtemGovorov** [comment]
Sorry for the delayed response. Yep, that's exactly what I'm using. If you'd like to make them clickable, here is what I do:
``` JavaScript
      var wallabyGutter = editor.addGutter({name: 'wallaby'});
      var wallabyGutterView = $(atom.views.getView(wallabyGutter));
      wallabyGutterView.on('click', '.decoration', e => {
        var line = e.target.children[0].dataset.line;
        // passing the line number further
      });
```
