### ISSUE TITLE
Setting it up with requirejs?

### ISSUE THREAD

**Issue by nim23** [wallabyjs/atom-wallaby#2]
I am aware of blog post being written about setting it up with existing project, but thought might as well open a ticket and ask for guidelines on setting it up with requirejs project.

**Comment by ArtemGovorov** [comment]
This [detailed guidelines](http://wallabyjs.com/docs/integration/requirejs.html) will help you to set it up for your require.js project. Let me know if it helps.

**Comment by nim23** [comment]
My project setup is a bit complicated, I did get it working momentarily but then I changed some config and ended up nowhere. Is there anyway to turn debugging on and see what error's are being thrown.

**Comment by ArtemGovorov** [comment]
Yes, you may set the [`debug` flag to `true`](http://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information). Then open DevTools in Atom (`Cmd + Alt + I` or whatever the shortcut is on your OS) and go to Console tab to see the detailed output.

**Comment by ArtemGovorov** [comment]
@nim23  Did you make it work? Can I provide more help or close the issue?

**Comment by nim23** [comment]
@ArtemGovorov it was a hit an miss for me, mostly due to the complicated nature of the project and custom implementation's. Please close the issue for now. I will dig further to make it work, I will give it another try this weekend.

**Comment by ArtemGovorov** [comment]
@nim23 No worries, please let me know if you hit any issues that you can share, will be glad to help.
