### ISSUE TITLE
Always get the "No valid license" error even with valid license

### ISSUE THREAD

**Issue by prabinv** [wallabyjs/atom-wallaby#22]
I've not been able to run Wallaby in Atom as I keep getting the `No valid wallaby.js license`, although I have a valid license. Not sure why this is happening, I tried uninstalling and reinstalling the package, but I still get the same error. I'm running Atom v1.1.0 on Mac OS X El Capitan.
![screen shot 2015-11-05 at 8 15 45 am](https://cloud.githubusercontent.com/assets/306468/10970731/2ff147a0-8396-11e5-8319-f0e9fe45799d.png)

**Comment by ArtemGovorov** [comment]
According to our system, your license is IntelliJ platform license, so you may only use it in WebStorm, IntelliJ IDEA, PhpStorm, RubyMine, and PyCharm. If you'd like to use wallaby.js in Atom you need to [purchase a license for Atom or 'Freedom' license](http://wallabyjs.com/#pricing) that works in all editors that we support.
