### ISSUE TITLE
Received "SyntaxError: Parse error" without any stack

### ISSUE THREAD

**Issue by MacsDickinson** [wallabyjs/atom-wallaby#26]
>Test run failure: Received `SyntaxError: Parse error` without any stack.
>Most likely the error is raised by PhantomJs during JavaScript code parsing stage.
>Unfortunately no additional details are provided (https://github.com/ariya/phantomjs/issues/11640).
>It is recommended to carefully review recent changes to find the error reason and source.

The issue referenced in this error has been closed. The fix will be included in PhantomJS version 2 which doesn't look to be available yet. Raising this to look into upgrading PhantomJS when 2.0 is out.

**Comment by ArtemGovorov** [comment]
Wallaby.js [supports PhantomJs2](http://wallabyjs.com/docs/integration/phantomjs2.html). The 1.9.8 is the default one because many people are still using it.

**Comment by MacsDickinson** [comment]
Great, thanks
