### ISSUE TITLE
wallaby.js changes __dirname

### ISSUE THREAD

**Issue by aaronjensen** [wallabyjs/atom-wallaby#3]
I can't reference example files w/ relative paths via `__dirname` as it seems to copy it into my `projects/.../instrumented/specs` dir

**Comment by ArtemGovorov** [comment]
Relative paths shouldn't be an issue because wallaby copies all files listed in `files` list of your config to that folder. Could you please provide some details about what errors are you getting and share your wallaby config file?

**Comment by aaronjensen** [comment]
I added those files to my `files` option and it made it work. I didn't realize I needed to add all files, I just added js files.

**Comment by migg24** [comment]
I stumbled upon the same issue. I have regression tests that have JSON files in the test directory, that have the complete expected response in them. Until I read this comment I did not recognize that I have to include the `**/*.json` into the `files` list. They are stored in the `test` directories and loaded from there.

I think this should be made more clear in the documentation that you have to include all files that are *used* by your tests into the `files` config. The documentation right now only states that "The files property should list your source files", and the JSON files that store the expected results of my tests are not my source files.

**Comment by ArtemGovorov** [comment]
@migg24 The [docs for node.js are saying](http://wallabyjs.com/docs/integration/node.html#files) that you have to list all files used by tests. I have added the same note to the JetBrains tutorial.

**Comment by ArtemGovorov** [comment]
@migg24 Oh, you must be talking about loading files from browser tests? Will add a note for them as well.

**Comment by ArtemGovorov** [comment]
@migg24 BTW, I'd avoid using the `**/*.json` pattern as it may include more files than you actually need (such as all JSON files from your `node_modules` folder, etc.). Based on how you've described your file structure, `test/**/*.json` pattern should be enough.

**Comment by migg24** [comment]
Thanks for clarification. I do not really use the pattern `**/*.json`, I use the sub paths, but did not think they belong here.
