### ISSUE TITLE
Uncaught TypeError: _(...).sortBy(...).each(...).value is not a function

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/atom-wallaby#30]
[Enter steps to reproduce below:]

1. Add non compilable typescript file
2. Run wallaby

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package, v1.0.7

### Stack Trace

Uncaught TypeError: _(...).sortBy(...).each(...).value is not a function

```
At /Users/tomi/.atom/packages/atom-wallaby/wallaby-atom/index.js:14

TypeError: _(...).sortBy(...).each(...).value is not a function
    at b.g.value (/Users/tomi/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:16936)
    at b.<anonymous> (/Users/tomi/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:6994)
    at emitTwo (events.js:92:20)
    at b.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/Users/tomi/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:10913)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter._.extend._documentUpdates (/Users/tomi/.atom/packages/atom-wallaby/wallaby/client.js:14:3743)
    at ChildProcess.<anonymous> (/Users/tomi/.atom/packages/atom-wallaby/wallaby/client.js:14:1289)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -1:03.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:57.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:55.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -0:55.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:54.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:54.9.0 wallaby:start (atom-text-editor.editor)
     -0:38.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:35.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.6.0 linter:lint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      ".bin",
      "refactor",
      "js-refactor",
      "ide-flow",
      "linter-flow",
      "tree-view-git-modified",
      "editorconfig"
    ],
    "ignoredNames": [
      ".DS_Store",
      ".git"
    ],
    "themes": [
      "one-dark-ui",
      "atom-monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
atom-macros, v0.5.2
atom-monokai, v0.9.7
atom-typescript, v8.3.0
atom-wallaby, v1.0.7
docblockr, v0.7.3
esformatter, v1.22.0
file-icons, v1.6.17
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-coffeescript, v1.0.0
linter-eslint, v7.0.0
linter-tslint, v0.8.3
minimap, v4.19.0
minimap-linter, v1.1.1
package-manager-commands, v2.0.3
project-manager, v2.7.6
react, v0.14.1
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by ArtemGovorov** [comment]
Could you please share an example of a TypeScript file where I could reproduce the issue?

**Comment by borisyankov** [comment]
I get the same error for an ES6 file. Complex project, can't isolate.

**Comment by ArtemGovorov** [comment]
@borisyankov Was the ES6 file in some invalid state (had an invalid syntax) when the error occurred?

**Comment by borisyankov** [comment]
I don't think so. Running npm test from the command line passes successfully (so does the webpack run)
This appeared in the latest release.

**Comment by ArtemGovorov** [comment]
@borisyankov So when does the error show up, when you start wallaby initially? Does it work ok after the error (ie. can you keep editing files without any issues after the error)?

**Comment by ArtemGovorov** [comment]
Ok, I have reproduced the issue and it's fixed in the wallaby plugin for Atom v1.0.20. It's the separately updatable plugin part (not the package itself), so no need to update anything manually, it should be updated automatically within the next 20 minutes. To force the update without having to wait, open `/Users/user/.atom/packages/atom-wallaby`, delete the `wallaby-atom` folder in there and restart Atom.

**Comment by borisyankov** [comment]
Great! Works.

**Comment by tomitrescak** [comment]
Great. Thanks!

**Comment by Jakehp** [comment]
I am currently getting this error. Any help would be appreciated @ArtemGovorov 

Ubuntu 14.04 LTS
Atom: 1.6.2
Wallaby: 1.0.7

```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Ubuntu 14.04.4
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package, v1.0.7


### Stack Trace

Uncaught TypeError: _(...).sortBy(...).each(...).value is not a function

```
At /home/jake/.atom/packages/atom-wallaby/wallaby-atom/index.js:14

TypeError: _(...).sortBy(...).each(...).value is not a function
    at b.g.value (/home/jake/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:16849)
    at b.<anonymous> (/home/jake/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:6994)
    at emitTwo (events.js:87:13)
    at b.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/home/jake/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:10913)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter._.extend._documentUpdates (/home/jake/.atom/packages/atom-wallaby/wallaby/client.js:14:3741)
    at ChildProcess.<anonymous> (/home/jake/.atom/packages/atom-wallaby/wallaby/client.js:14:1287)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -9:45.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -9:44.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -9:24.4.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -9:22.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -8:45.8.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -8:26.7.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -8:24.8.0 core:save (atom-text-editor.editor.is-focused)
     -4:14.8.0 core:close (div.package-detail.panels-item)
  2x -4:13.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:10.8.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:13.2.0 core:close (div.package-detail.panels-item)
     -0:09.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.1
atom-wallaby, v1.0.7
linter, v1.11.4
linter-jscs, v3.4.10

# Dev
No dev packages
```

**Comment by Jakehp** [comment]
I updated node to 4.4.2 and everything now works as intended.

**Comment by ArtemGovorov** [comment]
@Jakehp Thanks for the update! Not sure how node upgrade could help though, perhaps wallaby was automatically updated behind the scenes as well.

**Comment by Jakehp** [comment]
Yes wallaby did update. A notification window mentioned that.

The wallaby update that fixes this bug maybe required a certain version of node?

**Comment by ArtemGovorov** [comment]
> The wallaby update maybe required a certain version of node?

Shouldn't need it. It's just the automatic update is triggered not immediately after your editor restarts, but in a few minutes after you launch wallaby the first time after the editor restart (so that if you don't start wallaby, we don't slow the editor down with update checks, and if you do we do it in a background not to slow down your work with it).

**Comment by Jakehp** [comment]
Ahhh ok good to know. Thanks for responding so quickly. Love wallaby :+1:
