### ISSUE TITLE
Error "describe is not defined"

### ISSUE THREAD

**Issue by yamsellem** [wallabyjs/atom-wallaby#46]
Hi, 

I'm using wallaby with this configuration and getting the odd error, "describe is not defined" pointing to the first test it finds.

``` javascript
module.exports = function() {
    return {
        files: [
            'lib/**/*.js'
        ],

        tests: [
            'test/unit/**/*-test.js'
        ],

        env: {
            type: 'node',
            params: {
                env: 'NODE_ENV=test'
            }
        }
    };
};
```

**Comment by ArtemGovorov** [comment]
Hi,

What's the output in [the Wallaby Console](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting)?

**Comment by jsvanilla** [comment]
I have the same problem with VS-Code  create-react-app --typescript aplication when i open the app.test.ts file


<img width="456" alt="Captura de Pantalla 2021-09-26 a la(s) 5 21 27" src="https://user-images.githubusercontent.com/36719905/134803830-13489c00-5e5b-45d2-b651-8b720164c02b.png">

**Comment by jsvanilla** [comment]
<img width="613" alt="Captura de Pantalla 2021-09-26 a la(s) 5 23 23" src="https://user-images.githubusercontent.com/36719905/134803873-ba03bd17-7dbe-47d9-b423-4e84bb313f3f.png">

**Comment by ArtemGovorov** [comment]
@jsvanilla Can you please create an issue here at https://github.com/wallabyjs/public/issues/new and share your Wallaby Diagnostic report as described in the issue template?
