### ISSUE TITLE
Keybindings shift-cmd-t conflict

### ISSUE THREAD

**Issue by jeansebb** [wallabyjs/atom-wallaby#49]
On MacOSX with Atom, the core keybindings of shift-cmd-t reopen closed tabs. 

Can't even trigger the Wallabyjs keybindings.

**Comment by ArtemGovorov** [comment]
Hm, I'm using MacOSX, but I have no conflicts with keybindings in freshly installed Atom. The Key Binding Resolver in Atom also doesn't show any conflicts:

<img width="1138" alt="screen shot 2016-11-12 at 10 36 51 am" src="https://cloud.githubusercontent.com/assets/979966/20234206/1f02a70a-a8c4-11e6-8bdf-4b001e0dff06.png">

We've also never heard about the issue from any of our users. Perhaps it's some package you have installed and not the core keybindings? Could you please run the Key Binding Resolver in Atom to see what exactly conflicts with wallaby shortcut?
