### ISSUE TITLE
Deprecated selector in `atom-wallaby/styles/wallaby.atom-text-editor.less`

### ISSUE THREAD

**Issue by dsifford** [wallabyjs/atom-wallaby#50]
In `atom-wallaby/styles/wallaby.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.atom-text-editor .line.wlc::after,
:host .line.wlc::after` => `.atom-text-editor .line.wlc::after,atom-text-editor .line.wlc::after`

* `.atom-text-editor .line.wle::after,
:host .line.wle::after` => `.atom-text-editor .line.wle::after,atom-text-editor .line.wle::after`

* `.atom-text-editor .wallaby-cov,
:host .wallaby-cov` => `.atom-text-editor .wallaby-cov,atom-text-editor .wallaby-cov`

* `.atom-text-editor .wallaby-cov-1,
:host .wallaby-cov-1` => `.atom-text-editor .wallaby-cov-1,atom-text-editor .wallaby-cov-1`

* `.atom-text-editor .wallaby-cov-2,
:host .wallaby-cov-2` => `.atom-text-editor .wallaby-cov-2,atom-text-editor .wallaby-cov-2`

* `.atom-text-editor .wallaby-cov-3,
:host .wallaby-cov-3` => `.atom-text-editor .wallaby-cov-3,atom-text-editor .wallaby-cov-3`

* `.atom-text-editor .wallaby-cov-4,
:host .wallaby-cov-4` => `.atom-text-editor .wallaby-cov-4,atom-text-editor .wallaby-cov-4`

* `.atom-text-editor .wallaby-cov-5,
:host .wallaby-cov-5` => `.atom-text-editor .wallaby-cov-5,atom-text-editor .wallaby-cov-5`

* `.atom-text-editor .highlight.uncovered .region,
:host .highlight.uncovered .region` => `.atom-text-editor .highlight.uncovered .region,atom-text-editor .highlight.uncovered .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by ArtemGovorov** [comment]
Thanks I published the new 1.0.14 version, however I have left the old selector for backwards compatibility, so the deprecation warning will still show up until such time when `Automatic translation of selectors will be removed in a few release cycles`.
