### ISSUE TITLE
Wallaby client gets corrupted when two windows try to update at the same time

### ISSUE THREAD

**Issue by subblue** [wallabyjs/atom-wallaby#51]
Just a heads up...  
I had an odd issue after starting up Atom. It opened two windows for the last two projects I've been working on as expected, but both tried to update the Wallaby client at the same time, the second one throwing an error that it couldn't extract the package properly.
After that Wallaby was failing to start as it claimed it couldn't find the client. An uninstall and reinstall fixed it.

**Comment by ArtemGovorov** [comment]
Good catch! Thanks for the report, will try to reproduce it and see how to fix it.

**Comment by ArtemGovorov** [comment]
The issue should be fixed in atom-wallaby 1.0.19.
