### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by jonalu** [wallabyjs/atom-wallaby#54]
> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--.

At the time of writing Atom will automatically translate the unsupported selectors, but this will be removed in a few release cycles.

**Comment by ArtemGovorov** [comment]
Thanks for the report. There's a pending pull request https://github.com/wallabyjs/atom-wallaby/pull/53 that will address it once merged.
