### ISSUE TITLE
Deprecated selector in `atom-wallaby\styles\wallaby.atom-text-editor.less`

### ISSUE THREAD

**Issue by ummahusla** [wallabyjs/atom-wallaby#55]
In `atom-wallaby\styles\wallaby.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.atom-text-editor .line.wlc::after,
:host .line.wlc::after,
atom-text-editor .line.wlc::after` => `.atom-text-editor .line.wlc::after,atom-text-editor .line.wlc::after,
atom-text-editor .line.wlc::after`

* `.atom-text-editor .line.wle::after,
:host .line.wle::after,
atom-text-editor .line.wle::after` => `.atom-text-editor .line.wle::after,atom-text-editor .line.wle::after,
atom-text-editor .line.wle::after`

* `.atom-text-editor .wallaby-cov,
:host .wallaby-cov,
atom-text-editor .wallaby-cov` => `.atom-text-editor .wallaby-cov,atom-text-editor .wallaby-cov,
atom-text-editor .wallaby-cov`

* `.atom-text-editor .wallaby-cov-1,
:host .wallaby-cov-1,
atom-text-editor .wallaby-cov-1` => `.atom-text-editor .wallaby-cov-1,atom-text-editor .wallaby-cov-1,
atom-text-editor .wallaby-cov-1`

* `.atom-text-editor .wallaby-cov-2,
:host .wallaby-cov-2,
atom-text-editor .wallaby-cov-2` => `.atom-text-editor .wallaby-cov-2,atom-text-editor .wallaby-cov-2,
atom-text-editor .wallaby-cov-2`

* `.atom-text-editor .wallaby-cov-3,
:host .wallaby-cov-3,
atom-text-editor .wallaby-cov-3` => `.atom-text-editor .wallaby-cov-3,atom-text-editor .wallaby-cov-3,
atom-text-editor .wallaby-cov-3`

* `.atom-text-editor .wallaby-cov-4,
:host .wallaby-cov-4,
atom-text-editor .wallaby-cov-4` => `.atom-text-editor .wallaby-cov-4,atom-text-editor .wallaby-cov-4,
atom-text-editor .wallaby-cov-4`

* `.atom-text-editor .wallaby-cov-5,
:host .wallaby-cov-5,
atom-text-editor .wallaby-cov-5` => `.atom-text-editor .wallaby-cov-5,atom-text-editor .wallaby-cov-5,
atom-text-editor .wallaby-cov-5`

* `.atom-text-editor .highlight.uncovered .region,
:host .highlight.uncovered .region,
atom-text-editor .highlight.uncovered .region` => `.atom-text-editor .highlight.uncovered .region,atom-text-editor .highlight.uncovered .region,
atom-text-editor .highlight.uncovered .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by ummahusla** [comment]
After a quick research, I found the fix in #53 which hasn't been merged yet.

**Comment by ArtemGovorov** [comment]
Yep, will merge it later. It shouldn't break any way even when it's deprecated, because there's a correct style in place as well.

**Comment by ummahusla** [comment]
@ArtemGovorov Okay, thanks 👍

**Comment by Prashanfdo** [comment]
Atom has disabled the package since its deprecated.

**Comment by ArtemGovorov** [comment]
@Prashanfdo What version of Atom is it?

**Comment by Prashanfdo** [comment]
Version 1.16.0 on Windows 10

**Comment by Prashanfdo** [comment]
![image](https://cloud.githubusercontent.com/assets/890535/25079866/b7d72d8e-235d-11e7-8129-087800808b72.png)

**Comment by ArtemGovorov** [comment]
@Prashanfdo Try updating wallaby package to the latest, we have fixed it.

**Comment by Prashanfdo** [comment]
Updated to 1.0.17 
No deprecation now. Super 👍
