### ISSUE TITLE
Weird issue with wallaby's updated notification badge

### ISSUE THREAD

**Issue by ummahusla** [wallabyjs/atom-wallaby#56]
I've noticed that every time I pressed either **Start** or **Stop** I get a notification about wallaby's successful update.

____

**Notification**

```
Wallaby.js has been successfully updated
Atom plugin v1.0.31, Core v1.0.370
``` 

**Demo**

![](https://d17oy1vhnax1f7.cloudfront.net/items/460q0E021N1Y132c1E3M/Screen%20recording%202017-02-03%20at%2002.38.52%20PM.gif?v=93922142)

**Comment by ArtemGovorov** [comment]
Thanks for the report. Does the issue disappear when you restart Atom?

**Comment by ummahusla** [comment]
@ArtemGovorov I found this issue on my work Windows PC, so will need to wait for a Monday to give it a try. As far as I can remember I was restarting it several times.

**Comment by ArtemGovorov** [comment]
I think we've found the issue and fixed it. Please re-install wallaby Atom package (even though it's the same version), and it should disappear.
