### ISSUE TITLE
Failure using headless chrome on Linux

### ISSUE THREAD

**Issue by paulequilibrio** [wallabyjs/atom-wallaby#59]
Hi, I'm trying to use headless chrome in my tests but the wallaby console just show:

`Test run failure: Sandbox load failed, status: failed: Chrome is not running`

The relevant part of my wallaby.js is:

    env: {
      kind: 'chrome',
      runner: 'google-chrome-stable'
    }

My Chrome is `version 61.0.3163.79 (Official Build) (64-bit)` on Linux.
Doesn't matter if chrome is running or not, I always receive that message.

**Comment by ArtemGovorov** [comment]
Try removing the `runner: 'google-chrome-stable'` bit.

**Comment by ArtemGovorov** [comment]
Also please 
- try the [latest version of wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) I have just published (updated to the latest version of `chrome-launcher`),
- paste the full output from your wallaby console (perhaps there are some other related error messages there),
- in a new scratch project, try installing [this module](https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher) and running [one of the examples](https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher#examples) to see if it's working for you, or throwing some errors.

**Comment by paulequilibrio** [comment]
The full output from my wallaby console is just that:

    Test run failure: Sandbox load failed, status: failed: Chrome is not running

I followed all your suggestions. The output from

```javascript
const chromeLauncher = require('chrome-launcher');

chromeLauncher.launch({
  startingUrl: 'https://google.com'
}).then(chrome => {
  console.log(`Chrome debugging port running on ${chrome.port}`);
});
```

was

```shell
grep: ~/.local/share/applications/epiphany-google.com.br-f59615ee4cedf6fb88d4d09b43f8641a3f0d478b.desktop: No such file or directory
not found: chromium-browser
not found: chromium
```
After that I installed chromium, but the failure persist.

**Comment by ArtemGovorov** [comment]
Looks like Chrome launcher is [adding the `--disable-setuid-sandbox` flag in addition to the flags passed from outside](https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/chrome-launcher.ts#L129-L132), so there must be a reason why Chrome team is doing it and are making this flag not optional. I'd recommend raising an issue it the launcher repo about it.

Having said that, there is way in wallaby to override this behaviour if you like. In your wallaby config, you may intercept process `spawn` calls made by chrome launcher and just remove the flag:

```javascript
const cp = require('child_process');
const spawn = cp.spawn;
cp.spawn = function () {
  const flags = arguments[1];
  if (flags.length) {
    arguments[1] = flags.filter(f => f !== '--disable-setuid-sandbox');
  }
  return spawn.apply(this, arguments);
};

// the rest of your wallaby config
module.exports = function (wallaby) {
  ...
};
```

**Comment by paulequilibrio** [comment]
Thanks for your quick responses!
Your workaround works fine for me here.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
