### ISSUE TITLE
License does not seem to activate with atom

### ISSUE THREAD

**Issue by vreddi** [wallabyjs/atom-wallaby#63]
@ArtemGovorov 

I used to work with Visual Studio and my wallaby license worked fine in there. But in atom the activation of the wallaby license does not seem to work.

After I paste and apply the license, there is no notification that tells me the process succeeded or failed.
It seems to fail but I don't understand why.

**Comment by ArtemGovorov** [comment]
Perhaps your license was purchased for Atom only? Anyway, please send us your license key to hello@wallabyjs.com and we will sort it out for you.
