### ISSUE TITLE
Cannot create 'wallaby.json' on initial boot behind corporate proxy

### ISSUE THREAD

**Issue by thejamespower** [wallabyjs/atom-wallaby#65]
After running atom-wallaby for the first time I recieve the following error: 
```
.atom\packages\atom-wallaby\wallaby.json: Unexpected token < in JSON at position 0
```

Opening the mentioned file shows an HTML response from the corporate proxy I am unfortunately sat behind, stating my proxy login credentials are invalid.
Firstly, this json is created on the initialising of atom-wallaby. What is it doing?
Secondly, why is it connecting to the internet?
Finally, if this package needs to connect to the internet, shouldn't it be using the proxy and/or registry settings defined for Atom (i.e .apmrc)?

**Comment by ArtemGovorov** [comment]
> Firstly, this json is created on the initialising of atom-wallaby. What is it doing?
> Secondly, why is it connecting to the internet?

Wallaby plugin needs to download the [latest version of Wallaby Core](https://wallabyjs.com/docs/intro/how-it-works.html). The core is versioned and updated separately from the plugin itself.

> Finally, if this package needs to connect to the internet, shouldn't it be using the proxy and/or registry settings defined for Atom (i.e .apmrc)?

Please use the [instructions here](https://github.com/wallabyjs/public/issues/312#issuecomment-152145699) to configure wallaby/Atom to use your proxy settings.
