### ISSUE TITLE
There should be some sort of indication when there is a compile error

### ISSUE THREAD

**Issue by aaronjensen** [wallabyjs/atom-wallaby#7]
Right now, if you have a compiler error, it outputs to the console, but if you don't have that open, wallaby just looks like it is spinning forever.

**Comment by ArtemGovorov** [comment]
@aaronjensen Does it happen with Babel compiler errors? I have tried a few errors, but all of them make the indicator red. Am I reproducing the issue correctly and if so, could you please paste a sample error that makes the indicator to spin forever (until fixed)?
![i](https://cloud.githubusercontent.com/assets/979966/9707753/67daa5fa-5554-11e5-9b54-8adf63294389.gif)

**Comment by aaronjensen** [comment]
Not at a computer, but if I remember correctly , it was an error in my webpack config which was required by my wallaby conf 



Aaron

**Comment by ArtemGovorov** [comment]
Still no luck reproducing it yet, here is what I do now: making a syntax error in [webpack config file](https://github.com/aaronjensen/wallaby-line-number-repro/blob/master/webpack.wallaby.config.js) (which is required from wallaby config), saving it, re-running wallaby. Seems to work as expected:
![i](https://cloud.githubusercontent.com/assets/979966/9710097/a1f76578-5579-11e5-9cb3-0fb3026fbbb2.gif)

**Comment by aaronjensen** [comment]
I can't reproduce this anymore, it seems to work as expected now. I'll re-open if I see it again. Thanks!
