### ISSUE TITLE
How to reset license from open source to trial?

### ISSUE THREAD

**Issue by rodoabad** [wallabyjs/atom-wallaby#71]
I do have some non-open source projects and I want to switch the license from open to trial. Is there anyway to do that in IntelliJ/VSCode/Atom? Right now Wallaby thinks all my projects are open source and it is not able to verify (obviously) if it's a closed project.

**Comment by smcenlly** [comment]
You may also press the `Cmd/Ctrl + Shift + P` key combo to show the editor Command Palette and invoke the `Wallaby: Show License` command to display the license activation window. Once there, paste your trial license key.

If that does not work for you, please delete your the `.wallaby` directory from your home directory first (`~/.wallaby`) and then try again.
