### ISSUE TITLE
parameter merging error

### ISSUE THREAD

**Issue by deeperx** [wallabyjs/atom-wallaby#8]
In http://coffeescript.org 's 'try coffee script' section, I can use the code without any problem. But, within wallaby it throws an error (my linter also throws an error). It may be because of the coffee script version that wallaby uses. Is there a way to change the version? And how to get rid of this error?

**CODE:**

```coffeescript
class Foo
  constructor: (parameters = {}) ->
    {
      @id = 0
      @width  = 320
      @height = 200
    } = parameters

console.log new Foo({width: 500})
```

**ERROR:**

```
Failed to run compilers on test/firstTest.coffee, test/firstTest.coffee:16:11: error: unexpected =
      @id = 0
          ^
```

**Comment by ArtemGovorov** [comment]
CoffeeScript 1.10 was released a few days ago and it's a [new feature](http://coffeescript.org/#changelog) of it, so as you have suggested it wasn't working because wallaby.js didn't support that version yet. Have added the 1.10 support to wallaby.js, should now work in core v1.0.98. 
Please let me know if it works for you now.

**Comment by deeperx** [comment]
I'm trying to update wallaby from Atom but it says it's in the latest version which is: 1.0.4 and so, does not make an update.

**Comment by ArtemGovorov** [comment]
There hasn't been any package updates, bit there's been wallaby core update. Wallaby.js core updates itself automatically, you may [read about it here](http://wallabyjs.com/docs/intro/install.html#atom). Open Dev Tools (`Cmd + Alt + I`) console to see the current core version, perhaps it's already updated, if not restart you Atom editor and wait for a few minutes.

**Comment by deeperx** [comment]
Yes it shows that the _core_ version is: 1.0.98. But, I'm still probably getting the same error.

```javascript
Wallaby Failing Tests: Failed to run compilers on test/mine/firstTest.coffee, test/mine/firstTest.coffee:48:11: error: "1" cannot be assigned
      @a: 1
          ^/Users/me/.atom/packages/atom-wallaby/wallaby-atom/index.js:8 (anonymous function)
events.js:77 
emitOneevents.js:166 
emit/Users/me/.atom/packages/atom-wallaby/wallaby-atom/index.js:8 (anonymous function
)
events.js:77 
emitOneevents.js:166 
emit/Users/me/.atom/packages/atom-wallaby/wallaby/client.js:8 1._.extend._stats/Users/me/.atom/packages/atom-wallaby/wallaby/client.js:8 
(anonymous function)
events.js:87 
emitTwoevents.js:169 
emitchild_process.js:306 
handleMessagechild_process.js:334 
channel.onread
```

**Comment by ArtemGovorov** [comment]
It doesn't look like the same error, the message is different. Could you please share your not working code snippet?

**Comment by deeperx** [comment]
Sure.

```coffee script
class Image
  constructor: (options = {}) ->
    {
      @a: 1
      @b: '2'
    } = options

new Image()
```

**Comment by ArtemGovorov** [comment]
It doesn't seem like a valid CoffeeScript (doesn't work in http://coffeescript.org 's 'try coffee script' section either). I'm guessing it should be:
``` CoffeeScript
class Image
  constructor: (options = {}) ->
    {
      @a = 1
      @b = '2'
    } = options

new Image()
```

**Comment by deeperx** [comment]
Sorry, my mistake. I've tried the new code but it's getting the first error: ```error: unexpected =```. But, it works in try coffee script without a problem.

**Comment by ArtemGovorov** [comment]
Strange, could you please uninstall wallaby.js package from Atom and install it again? It works for me, so the only guess I have why it doesn't for you is that because there's were some issues in updating the core.
<img width="313" alt="screen shot 2015-09-07 at 6 24 16 pm" src="https://cloud.githubusercontent.com/assets/979966/9712520/8a7f535a-558e-11e5-86f3-e6edf0a837e1.png">
